import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { MyQueryClientProvider } from "@/providers/query-client";
import { AuthProvider } from "@/contexts/AuthContext";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${nunitoSans.className}`}>
        <MyQueryClientProvider>
          <AuthProvider>{children}</AuthProvider>
        </MyQueryClientProvider>
      </body>
    </html>
  );
}
